---
- name: Include vars
  ansible.builtin.include_vars: vars.yaml

- name: Install the latest version of podman
  package:
    name: podman
    state: latest
  when: (ignore_packages is not defined or not (ignore_packages | bool))

- name: show podman version
  shell: podman --version

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
  shell: curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394 part 2
  shell: dpkg -i containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install the latest version of aardvark-dns
  package:
    name: aardvark-dns
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '24.04'

- name: Install the latest version of uidmap
  package:
    name: uidmap
    state: latest
  when: (ignore_packages is not defined or not (ignore_packages | bool)) and (ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '22.04')

- name: Install the latest version of slirp4netns
  package:
    name: slirp4netns
    state: latest
  when: (ignore_packages is not defined or not (ignore_packages | bool))

## pre-requisite for containers
- name: Create a podman network
  containers.podman.podman_network:
    name: pytroll_network
