---
- name: Include vars
  ansible.builtin.include_vars: vars.yaml

- name: Install the latest version of podman
  package:
    name: podman
    state: latest

- name: show podman version
  shell: podman --version

- name: Install the latest version of aardvark-dns
  package:
    name: aardvark-dns
    state: latest

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'

- name: Create local pyspectral directory
  file:
    path: "{{ install_dir }}/local/"
    state: directory
    mode: '0777'


- name: Create input directory
  file:
    path: "{{ input_dir }}"
    state: directory
    mode: '0755'

- name: Create output directory
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0777'

- name: Update the trollflow2 configuration
  git:
    repo: https://github.com/nordsat/ewc-config.git
    dest: "{{ install_dir }}"
  register: git_config_results
  failed_when:
    - git_config_results.failed
    - not 'Local modifications exist in repository' in git_config_results.msg

- name: copy the trollstalker configuration
  copy:
    src: trollstalker.ini
    dest: "{{ install_dir }}/config_fci_nc"
  register: trollstalker_config_results

- name: copy the segment-gatherer configuration
  copy:
    src: segment_gatherer.yaml
    dest: "{{ install_dir }}/config_fci_nc"
  register: segment_gatherer_config_results

- name: copy the environment configuration
  copy:
    src: env-variables
    dest: "{{ install_dir }}/config_fci_nc"
  register: environment_config_results

- name: Create a podman network
  containers.podman.podman_network:
    name: pytroll_network

- name: Pull the trollstalker image
  containers.podman.podman_image:
    name: docker.io/mraspaud/trollstalker:main
  register: trollstalker_image

- name: Print if container should be restarted
  ansible.builtin.debug:
    msg: "{{ (trollstalker_config_results.changed or trollstalker_image.changed) | bool }}"

- name: Restart the trollstalker
  containers.podman.podman_container:
    name: trollstalker-fci
    image: docker.io/mraspaud/trollstalker:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ (trollstalker_config_results.changed or trollstalker_image.changed) | bool }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc/,target=/config/"
      - "type=bind,source={{ input_dir }},target=/mnt/input/"
    rm: true
    network: pytroll_network

- name: Pull the segment-gatherer image
  containers.podman.podman_image:
    name: docker.io/mraspaud/segment-gatherer:main
  register: segment_gatherer_image

- name: Restart the segment-gatherer
  containers.podman.podman_container:
    name: segment-gatherer-fci
    image: docker.io/mraspaud/segment-gatherer:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ segment_gatherer_config_results.changed or segment_gatherer_image.changed }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc/,target=/config/"
    rm: true
    network: pytroll_network

- name: Pull the trollflow2 image
  containers.podman.podman_image:
    name: docker.io/mraspaud/trollflow2:main
    force: true
  register: trollflow2_image

- name: Restart trollflow2
  containers.podman.podman_container:
    name: trollflow2-fci
    image: docker.io/mraspaud/trollflow2:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    #force_restart: "{{ trollflow2_image.changed or git_config_results.changed or environment_config_results.changed }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc/,target=/config/"
      - "type=bind,source={{ input_dir }},target=/mnt/input/"
      - "type=bind,source={{ output_dir }},target=/mnt/output/"
      - "type=bind,source={{ install_dir }}/local/,target=/.local/"
    rm: true
    network: pytroll_network
