---
- name: Include vars
  ansible.builtin.include_vars: vars.yaml

- name: Install the latest version of podman
  package:
    name: podman
    state: latest

- name: show podman version
  shell: podman --version

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
  shell: curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394 part 2
  shell: dpkg -i containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install the latest version of aardvark-dns
  package:
    name: aardvark-dns
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '24.04'

- name: Install the latest version of uidmap
  package:
    name: uidmap
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '22.04'

- name: Install the latest version of slirp4netns
  package:
    name: slirp4netns
    state: latest

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'

- name: Create input directory
  file:
    path: "{{ input_dir }}"
    state: directory
    mode: '0777'

- name: Set up cleaning of input directory
  cron:
    name: "Clean up input data directory"
    minute: "*/10"
    job: "cd {{ input_dir }}; find . -type f -mmin +120 -delete"

- name: Create output directory
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0777'

- name: Set up cleaning of output directory
  cron:
    name: "Clean up output data directory"
    minute: "15"
    job: "cd {{ output_dir }}; find . -type f -mtime +3 -delete"

- name: Update the trollflow2 configuration
  git:
    repo: https://github.com/nordsat/ewc-config.git
    dest: "{{ install_dir }}"
  register: git_config_results
  failed_when:
    - git_config_results.failed
    - not 'Local modifications exist in repository' in git_config_results.msg

- name: copy the environment configuration
  copy:
    src: env-variables
    dest: "{{ install_dir }}/config_fci_nc"
  register: environment_config_results

## pre-requisite for containers
- name: Create a podman network
  containers.podman.podman_network:
    name: pytroll_network

## Trollstalker

- name: copy the trollstalker configuration
  copy:
    src: trollstalker.ini
    dest: "{{ install_dir }}/config_fci_nc"
  register: trollstalker_config_results

- name: Pull the trollstalker image
  containers.podman.podman_image:
    name: docker.io/mraspaud/trollstalker:main
  register: trollstalker_image

- name: Print if container should be restarted
  ansible.builtin.debug:
    msg: "{{ (trollstalker_config_results.changed or trollstalker_image.changed) | bool }}"

- name: Restart the trollstalker (Ubuntu >= 24.04)
  containers.podman.podman_container:
    name: trollstalker-fci
    image: docker.io/mraspaud/trollstalker:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ (trollstalker_config_results.changed or trollstalker_image.changed) | bool }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc,target=/config/"
      - "type=bind,source={{ input_dir }},target=/mnt/input/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04")

- name: Restart the trollstalker (Ubuntu 22.04)
  containers.podman.podman_container:
    name: trollstalker-fci
    image: docker.io/mraspaud/trollstalker:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ (trollstalker_config_results.changed or trollstalker_image.changed) | bool }}"
    volumes:
      - "{{ install_dir }}/config_fci_nc:/config/"
      - "{{ input_dir }}:/mnt/input/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

## Segment Gatherer

- name: copy the segment-gatherer configuration
  copy:
    src: segment_gatherer.yaml
    dest: "{{ install_dir }}/config_fci_nc"
  register: segment_gatherer_config_results

- name: Pull the segment-gatherer image
  containers.podman.podman_image:
    name: docker.io/mraspaud/segment-gatherer:main
  register: segment_gatherer_image

- name: Restart the segment-gatherer (Ubuntu 24.04)
  containers.podman.podman_container:
    name: segment-gatherer-fci
    image: docker.io/mraspaud/segment-gatherer:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ segment_gatherer_config_results.changed or segment_gatherer_image.changed }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc/,target=/config/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04")

- name: Restart the segment-gatherer (Ubuntu >= 24.04)
  containers.podman.podman_container:
    name: segment-gatherer-fci
    image: docker.io/mraspaud/segment-gatherer:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ segment_gatherer_config_results.changed or segment_gatherer_image.changed }}"
    volumes:
      - "{{ install_dir }}/config_fci_nc/:/config/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

## Trollflow2

- name: Create local pyspectral directory
  file:
    path: "{{ install_dir }}/local/"
    state: directory
    mode: '0777'

- name: Pull the trollflow2 image
  containers.podman.podman_image:
    name: docker.io/mraspaud/trollflow2:main
    force: true
  register: trollflow2_image

- name: Restart trollflow2 (Ubuntu >= 24.04)
  containers.podman.podman_container:
    name: trollflow2-fci
    image: docker.io/mraspaud/trollflow2:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ trollflow2_image.changed or git_config_results.changed or environment_config_results.changed }}"
    mount:
      - "type=bind,source={{ install_dir }}/config_fci_nc/,target=/config/"
      - "type=bind,source={{ input_dir }},target=/mnt/input/"
      - "type=bind,source={{ output_dir }},target=/mnt/output/"
      - "type=bind,source={{ install_dir }}/local/,target=/.local/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
    env:
      GDAL_NUM_THREADS: "ALL_CPUS"
      NUM_THREADS: "ALL_CPUS"
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04")

- name: Restart trollflow2 (Ubuntu 22.04)
  containers.podman.podman_container:
    name: trollflow2-fci
    image: docker.io/mraspaud/trollflow2:main
    state: started
    # Does not have any effect because of https://github.com/containers/ansible-podman-collections/issues/355
    force_restart: "{{ trollflow2_image.changed or git_config_results.changed or environment_config_results.changed }}"
    volumes:
      - "{{ install_dir }}/config_fci_nc/:/config/"
      - "{{ input_dir }}:/mnt/input/"
      - "{{ output_dir }}:/mnt/output/"
      - "{{ install_dir }}/local/:/.local/"
    rm: true
    network: pytroll_network
    log_opt:
      max_size: 10mb
    env:
      GDAL_NUM_THREADS: "ALL_CPUS"
      NUM_THREADS: "ALL_CPUS"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
