---
- name: Include vars
  ansible.builtin.include_vars: vars.yaml

- name: Check if user lingering is enabled
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ ansible_user_id }}"
  register: user_lingering

- name: Warn if lingering is disabled
  ansible.builtin.debug:
    msg: "WARNING: Lingering is disabled. Services will not start at boot or persist after logout. Run 'sudo loginctl enable-linger {{ ansible_user_id }}' if possible."
  when: not user_lingering.stat.exists

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
  shell: curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: bug fix for ubuntu 22 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394 part 2
  shell: dpkg -i containernetworking-plugins_1.1.1+ds1-3build1_amd64.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install the latest version of aardvark-dns
  package:
    name: aardvark-dns
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '24.04'

- name: Install the latest version of uidmap
  package:
    name: uidmap
    state: latest
  when: (ignore_packages is not defined or not (ignore_packages | bool)) and (ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '22.04')

- name: Install the latest version of slirp4netns
  package:
    name: slirp4netns
    state: latest
  when: (ignore_packages is not defined or not (ignore_packages | bool))

- name: Get UID of the become user
  ansible.builtin.command: id -u
  register: user_id_result
  changed_when: false

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: "0777"

- name: Create pg-data directory
  file:
    path: "{{ install_dir }}/pg-data"
    state: directory
    #mode: '0777'

- name: install the init sql
  template:
    src: init.sql
    dest: "{{ install_dir }}"
  register: init_sql

- name: Update the trollflow2 configuration
  git:
    repo: https://github.com/nordsat/ewc-config.git
    dest: "{{ install_dir }}/config"
  register: git_config_results
  failed_when:
    - git_config_results.failed
    - not 'Local modifications exist in repository' in git_config_results.msg

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: "/etc/containers/systemd/users/{{ user_id_result.stdout }}"
    state: directory
    mode: "0755"

- name: Ensure Quadlet runtime directory exists
  ansible.builtin.file:
    path: "/run/user/{{ user_id_result.stdout }}"
    state: directory
    mode: "0755"

- name: Create Quadlet network file
  ansible.builtin.copy:
    dest: "/etc/containers/systemd/users/{{ user_id_result.stdout }}/pytroll.network"
    content: |
      [Network]
      NetworkName=pytroll_network
      [Install]
      WantedBy=default.target
  register: network_file

- name: Create Quadlet for postgis
  template:
    src: postgis.container.j2
    dest: "/etc/containers/systemd/users/{{ user_id_result.stdout }}/postgis-viirs.container"
  register: quad_postgis

- name: Create Quadlet for db-push
  template:
    src: db-push.container.j2
    dest: "/etc/containers/systemd/users/{{ user_id_result.stdout }}/db-push-viirs.container"
  register: quad_db_push

- name: install the db-push config file
  template:
    src: db-push.yaml
    dest: "{{ install_dir }}"
  register: dbpush_config

- name: Create Quadlet for sat-wms
  template:
    src: sat-wms.container.j2
    dest: "/etc/containers/systemd/users/{{ user_id_result.stdout }}/sat-wms-viirs.container"
  register: quad_sat_wms

- name: Ensure the latest postgis image is present
  containers.podman.podman_image:
    name: docker.io/postgis/postgis:latest
    force: yes # This forces a pull even if the tag is already present
  register: image_pull_postgis

- name: Ensure the latest image is present
  containers.podman.podman_image:
    name: "{{ docker_repo }}{{ item }}"
    force: yes # This forces a pull even if the tag is already present
  loop:
    - "db-push:main"
    - "sat-wms:main"
  register: image_pull

- name: Reload systemd to apply changes
  systemd:
    scope: user
    daemon_reload: yes
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_id_result.stdout }}"
  when: network_file.changed or quad_postgis.changed or quad_db_push.changed or quad_sat_wms.changed

- name: Ensure services are enabled and running
  ansible.builtin.systemd:
    scope: user
    name: "{{ item }}.service"
    state: started
    enabled: yes
  loop:
    - pytroll-network
    - postgis-viirs
    - db-push-viirs
    - sat-wms-viirs
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_id_result.stdout }}"

# Install the disk-cleaning script and schedule it via cron

- name: Install the VIIRS cleaning script
  template:
    src: "{{ playbook_dir }}/../common/templates/clean-output.sh.j2"
    dest: "{{ install_dir }}/clean-viirs.sh"
    mode: "0755"

- name: Schedule VIIRS output cleaning
  ansible.builtin.cron:
    name: "Clean VIIRS output directory"
    minute: "0,15,30,45"
    job: "{{ install_dir }}/clean-viirs.sh"
